### ISSUE TITLE
recurring event exception: moving event

### ISSUE THREAD

**Issue by gerhardmu** [jobisoft/TbSync#47]
on recurring events now the exception is supported that one event could be deleted, but moved events won´t be synched. On other clients this event remains as is.

**Comment by jobisoft** [comment]
more details, steps to reproduce please

**Comment by gerhardmu** [comment]
I am sorry, right. It is not a general problem. On Sogo it works. It is only a problem on MS Exchange: Establish a recurring event and move one of the following events. that changing is not synched on Exhange.

**Comment by jobisoft** [comment]
please give me the exact test case to reproduce, that fails with MS Exchange (2010?). Best drop the ICS of the original event here and than tell me, what event of the series you moved (to where?)

**Comment by ChrisJAllan** [comment]
I did some testing on Outlook, it seems that if an occurrence is moved before or after another occurrence, it causes issues. This may very well be Outlook's fault, as the server is sending sync data that disagrees with the web UI.

**Comment by jobisoft** [comment]
@gerhardmu: I get lots of bug reports by now and I no longer have the time to try to reproduce problems. Please help me by sending in a sample case. Create a recurring event, export it as ICS, post it here and tell me which event from the series I have to move where to trigger the bug.

Also, if you have such data, tell me which servers you tried and which failed. Thanks!



Am 05.02.18 um 23:29 schrieb Chris Allan

**Comment by gerhardmu** [comment]
I actually cannot say the version of Exchange which I am using. It is from https://hosting.1und1.de/microsoft-exchange, so probably version 2013

Now I did the following:

1) I went to Outlook Web App and added on browser a new calendar "test"
2) I added there a recurring event "Testrecurring". That was been synched with Thunderbird
3) I moved there the second date from 8 to 9. That was been synched with Thunderbird
4) I moved on Thunderbird the third date to 7
5) I established on Thunderbird a recurring event "Test Thunderbird" and moved the third date from 14.30 to 12. than I synchronized on Thunderbird and received error message (pls. find error.jpg and test.ics)
6) I deleted on Thunderbird the "Test Thunderbird" events completely and synched again. Now synching was shown to be successfully, but the modified date from point 4 was not synched to Exhange (pls. find test 2.ics)

![error](https://user-images.githubusercontent.com/35499060/35855247-efb48ae0-0b32-11e8-8e3f-64bd4e7482fc.jpg)

[Test.zip](https://github.com/jobisoft/TbSync/files/1698683/Test.zip)

**Comment by ChrisJAllan** [comment]
You cannot move an occurrence to before or after another occurrence. This is a limitation of Outlook. Try to make all of these changes on Outlook and then reload the page, some of the changes will be ignored.

It's probably possible to put in some sanity checks that catch and ignore these, but just know that it's not going to be perfect.

**Comment by gerhardmu** [comment]
@ChrisJAllan I am glad that you are doing that job, because I got rid of Outlook, but due to other reasons (exchange and sogo do not run on the same device, 2013 Outlook do not run when you have Office 2010 apps, and and and. It is not a thing about money, the product is annoying). However on that point I do not agree. On Outlook you can move occurrences where ever you want and it will be synchronized, also with TBsync when created in Outlook. It is possible to add and modify such events on Thunderbird, but it is not sychnronized with TBSync on some reasons which I do not know. However there seems to be a common accessible way to solve that, otherwise uncountable third party android calendar and iOS systems would not be able to work properly, but they do. I am using them.

**Comment by ChrisJAllan** [comment]
I am unable to move an occurrence past another occurrence in Office365 Outlook web interface, it gives me this error: 
![screen shot 2018-02-08 at 20 38 35](https://user-images.githubusercontent.com/9275775/36012012-27dbdb60-0d10-11e8-8a39-5164e2c5b3a0.png)

This was done by creating a weekly event on every Wednesday and modifying the occurrence on the 21st, renaming it "Not Wednesday," and moving it to the 12th. If this does work with other Outlook versions, then I don't know what to do. There's not really a way to ask the server which random features it doesn't support.

Interestingly enough, Outlook can import an ics of this event, but it splits the modification into a completely separate event. That would be a pain, but might be the best way to solve this.

**Comment by gerhardmu** [comment]
[Test 3.zip](https://github.com/jobisoft/TbSync/files/1710171/Test.3.zip)
strange. I did it successfully on OutlookWebApp (pls find test3.ics). It is also well synchronized to Outlook Desktop and Thunderbird. I heard about that is solved that way, that moved events will be created as new one. I am just not clear why this moved event nevertheless has relation to the recurring events, because when you want to edit it you will be ask whether you want to edit this single event or the recurring.

**Comment by jobisoft** [comment]
You two are using different systems so your experience will not match. @gerhardmu is using a real exchange server (hosted by 1&1) with OutlookWebApp and @ChrisJAllan is using an Office 365 server with the webinterface at outlook.office.com. 

You both must be more specific, when using the term "outlook", it could mean "Outlook Desktop", "Outlook web app" or "outlook.office.com". Did I forget one? 

The current status if this issue is as follows:
- you can move occurences out of order with TbSync and a SOGo account? (veriefied on the server?)
- you cannot move occurences out of order with TbSync and your 1&1 Exchange server account?

Is any other device (iPhone, Android) able to move an occurence out of order on your 1&1 Exchange server? Your Outlook Web App does not count, because that is probably not using EAS to communicate with your server.

**Comment by gerhardmu** [comment]
besides, probably another issue: When creating another calendar "test" on OutlookWebApp and when I force it to be  synched on Thunderbird I see that contacts are all doubled. After disconnection and connecting again, test is not synched any more and addresses are not doubled any longer

**Comment by jobisoft** [comment]
Do not mix issues.

**Comment by gerhardmu** [comment]
that is right:
- I can move occurences out of order with TbSync and a SOGo account, verified on the server
- I cannot move occurences out of order with TbSync and my 1&1 Exchange server account
pff, disconnecting and connecting several times led to the effect that a lot of occurences lost their day time specifications. now they are "whole day" events.

**Comment by jobisoft** [comment]
Regarding the last comment, Disconnecting and reconnecting is not sending anything to the server, I assume that the failed uploads somehow messed up the events.

Do not modify your events in TbSync any longer and disconnect your account. Fix your event data on the server. Than reconnect/disconnect many many times in TbSync to make sure that this is not causing event corruption.

If that is out of the way, we can move on.

**Comment by gerhardmu** [comment]
I should have fixed it now. I can proceed.

**Comment by jobisoft** [comment]
Thanks for your time and efforts. I have found something, where TbSync is not following the protocol and i will fix that (it does not follow the xml scheme: https://msdn.microsoft.com/en-us/library/dn338917(v=exchg.80).aspx). 

I report back, as soon as I have released the next beta.

**Comment by jobisoft** [comment]
Before I forget:

 - can you backup your calendar, so you can restore, if something goes bad again?
 - can you disable auto sync of the test account (set autosync to 0)?
 - can you connect/disconnect a couple of times, so we can rule out, this is corrupting your data as you observed?

**Comment by gerhardmu** [comment]
No I have done it as desired and all data are ok after that.

**Comment by jobisoft** [comment]
I just drop this here for later, do not know if related, this is from [evolution](https://raw.githubusercontent.com/GNOME/evolution-activesync/master/eas-daemon/libeas/eas-cal-info-translator.c)

// This is a bit tricky.
	//
	//  - If the EAS <Exception> element ONLY contains <ExceptionStartTime> and
	//    <Deleted> (with the latter's value set to 1), it's a simple exception
	//    that just deletes one of the occurrences of the recurrence (ie. an
	//    EXDATE in iCal);
	//
	//  - If it just contains an <ExceptionStartTime> (and optionally a <Deleted>
	//    element with the value 0), it represents an *additional* occurrence of
	//    the event, with all other attributes identical to those of the recurring
	//    event (ie. an RDATE in iCal);
	//
	//  - However, if it contains additional elements, it represents an exception
	//    where properties have been changed (eg. where the start time or subject
	//    have been changed for one occurrence only). These aren't supported in
	//    iCal so we have to create a whole new event. We can't do that here (as
	//    we're still part-way through parsing the event) so we return a list of
	//    exception event details so they can be processed later. Each exception
	//    event we return is stored as a hash table of property names/values.
	//    (So this function returns a list of hash tables.)

I am still stuck at a timezone problem, as soon as i fixed that, I will get back on this.

**Comment by ChrisJAllan** [comment]
I don't think that will help with this issue, which is iCal -> EAS, but it is interesting that EAS supports RDATEs, because those are currently ignored.

As for splitting unsupported items into separate events, I'm still not sure exactly what is and isn't supported as it seems that different servers support different things. I only have problems when an occurrence is moved past another occurrence, @gerhardmu are you having this issue with all moved exceptions? And also only on the Exchange server?

**Comment by gerhardmu** [comment]
I have this issue only on Exchange server when it is done on Thunderbird. When I modify events on Outlook (desktop and webapp), on Android or iPad it will be done for any device and in Thunderbird as well.
Probably it helps when you see such an event modified on Outlook desktop. This daily events start on 14th of march (today). Tomorrow it is  moved backwards, Friday deleted, Saturday moved forward.

[Kalender von Test4.zip](https://github.com/jobisoft/TbSync/files/1811239/Kalender.von.Test4.zip)

**Comment by jobisoft** [comment]
@ChrisJAllan : I would like to know, what you think about the following:

At current, we read the EAS data and merge that into Thunderbird events by using the lightning API (which is a mess, if you ask me). For my current task, for the first time I did something like this:

```
            //usning TB recurrence API to calculate actual date from RRULE
            let event = cal.createEvent();
            event.icalString = "BEGIN:VEVENT\n" + 
                "DTSTART:" + obj.dtstart + "\n" + 
                "RRULE:" + obj.rrule + "\n" + 
                "END:VEVENT";
            
            let nextTimeThisYear = event.recurrenceInfo.getNextOccurrence(cal.createDateTime("20180101T000000Z"));
```

My question: Would it be easier to create an icalString from the EAS data (including recurrence stuff like RDATE, RRULE and exceptions etc.) and "import" the event as above, instead of messing around with the lightning API?

**Comment by ChrisJAllan** [comment]
I don't see icalStrings as beaing easier, especially not for the entire event. However, individual components can be modified using icalStrings, for example, `"DTSTART:" + obj.dtstart + "\n"` is equivalent to `item.startDate = cal.createDateTime(obj.dtstart)` or `item.startDate.icalString = obj.dtstart;` if `item.startDate` already exists. RRULEs would take a few more steps, but can still be assigned directly from an icalString:
```js
item.recurrenceInfo = cal.createRecurrenceInfo();
item.recurrenceInfo.item = item;
let recRule = cal.createRecurrenceRule(obj.rrule);
item.recurrenceInfo.insertRecurrenceItemAt(recRule, 0);
```
So if it is easier in some cases, it is possible to use it only in those cases. Modification exceptions are stored as separate events, so it would take quite a bit more work to do them with only icalStrings.

**Comment by jobisoft** [comment]
I now have access to an Exchange Server I can confirm this. If I import your [ICS file](https://github.com/jobisoft/TbSync/issues/47#issuecomment-373021346), and try to sync that to the exchange server, the items are not accepted.

@ChrisJAllan : A possible fix would be - generally - to not move events around via exceptions (as now) but to delete it via EXDATE (which is possible now already) and to add it at the new location via RDATE (which should be possible as you said). Would you like to take this? Otherwise I will try to dig into your code :-)

**Comment by ChrisJAllan** [comment]
I have tried making this workaround at c9d7c5176700701343f453180df698955007260b, could you test it with Exchange? The RDATE method doesn't work with Office365, the changes are either rejected or silently ignored. The workaround can be toggled by line 780, so if it does work for Exchange it should be added as a setting.

**Comment by jobisoft** [comment]
Thanks for your time! 

Sadly, it does not work (silent ignore). I think the RDATE does not work. I am currently analyzing your code and play around with it, but simply adding an extra out-of-order item via Exception with delete=0 does not seem to work. I will investigate further.

**Comment by jobisoft** [comment]
I am puzzled. Microsoft products are the reference for me regarding EAS and none of the Microsoft products I have acces to, support moving an event of a series beyond the last or next recurrence. I tested:

- Office 365 WebPortal
- Outlook.com WebPortal
- Exchange 2010 WebPortal (Outlook WebApp)

@gerhardmu : This somehow contradicts your [finding](https://github.com/jobisoft/TbSync/issues/47#issuecomment-364087016)

It indeed works with other servers, which have their own EAS implementation:
- SOGO (syncing up and down)
- Tine 2.0 (syncing up and down)

Horde however is broken, the web interface is messing up the series, if you try to move it. I did not test any further.

**So my current status is: If the web interface does not support moving an event before or after the next regular recurrence, than TbSync will throw an error, if I try to sync such a modified series to the server. The server simply does not support it.**

@gerhardmu : Now you reported, that it does work with **your** Outlook WebApp. Lets concentrate on that. You may have answered these questions already, but lets just get it all together here:
 - What kind of server is it?
 - When you created such a problematic series in the web interface, does it sync down to Thunderbird?
 - If yes, please post the ApplicationData of that incoming ("receiving") event from the debug.log. 
 - Changing something in the series with Thunderbird  (for example the subject) without changing any dates, does that sync back to the server (and the web interface showing those changes)?  
 - What do you have to change in Thunderbird, so that it does not sync back to the server anymore?
 - Can I get access to that account to test myself?
 - Is there any other client (iPhone etc.) that is able to sync such a series to the server and the web interface is indeed showing the modification (my iPhone was not able to do that with my Exchange 2010)

**Comment by jobisoft** [comment]
Please use v0.7.6 for your tests!

**Comment by gerhardmu** [comment]
- What kind of server is it?
I use the exchange server from 1&1. It seems that they are using MS Exchange 2013

- When you created such a problematic series in the web interface, does it sync down to Thunderbird?
yes

- If yes, please post the ApplicationData of that incoming ("receiving") event from the debug.log.
[debug Test.txt](https://github.com/jobisoft/TbSync/files/1842056/debug.Test.txt)

- Changing something in the series with Thunderbird (for example the subject) without changing any dates, does that sync back to the server (and the web interface showing those changes)?
yes, renaming will be synched

- What do you have to change in Thunderbird, so that it does not sync back to the server anymore?
it is only the moving of a single event out of a serie

- Can I get access to that account to test myself?
unfortunatly not. It is my personnal account and I have none more, but I will help as I can

- Is there any other client (iPhone etc.) that is able to sync such a series to the server and the web interface is indeed showing the modification (my iPhone was not able to do that with my Exchange 2010)
I can move an event with all other apps on iPad and Android, Outlook and Outlook Webapp

**Comment by jobisoft** [comment]
Resolved via phone.
