### ISSUE TITLE
OAuth 2.0 authentication server returned: {} for Outlook Office365 mail

### ISSUE THREAD

**Issue by mdiskuze** [jobisoft/TbSync#645]
## Your environment

TbSync version: 4.3
Thunderbird version: 102.7.0 (64-bit) - Ubuntu 22.04.1
Provider for EAS: 4.1.5

## Expected behavior
All mails and calendar will be synchronized

## Actual behavior
When Thunderbird starts - he ask me for allowing access into my account (by mobile push notification, MS auth android app with user+pwd). Push notification is correctly processed and TB login window is closed. But after few seconds TB tells me:
![image](https://user-images.githubusercontent.com/13920503/213133648-23e61dc9-cf21-438f-90f5-9abab3b6a9ef.png)

When I try to connect thru TbSync:
![image](https://user-images.githubusercontent.com/13920503/213133864-3b808190-74e0-43cb-a9c0-2076e04a83b9.png)

Event log:
![image](https://user-images.githubusercontent.com/13920503/213134043-9fb80e52-f15e-44bf-86d5-0ee436781811.png)

Last lines from debug.log:
```** Wed Jan 18 2023 10:25:15 GMT+0100 (StYedoevropsk� standardn� 
as) **
[EventLog] : The IANA timezone <Europe/Kyiv> cannot be mapped to any Exchange timezone.

** Wed Jan 18 2023 10:25:15 GMT+0100 (StYedoevropsk� standardn� 
as) **
[EventLog] : The IANA timezone <Pacific/Kanton> cannot be mapped to any Exchange timezone.

** Wed Jan 18 2023 10:25:15 GMT+0100 (StYedoevropsk� standardn� 
as) **
[Loaded provider] : dav::CalDAV & CardDAV (4.3)

** Wed Jan 18 2023 10:25:15 GMT+0100 (StYedoevropsk� standardn� 
as) **
[Loaded provider] : eas::Exchange ActiveSync (4.1.5)

** Wed Jan 18 2023 10:27:11 GMT+0100 (StYedoevropsk� standardn� 
as) **
[setSyncState] : State: prepare.request.options, Account: M... T...

** Wed Jan 18 2023 10:27:11 GMT+0100 (StYedoevropsk� standardn� 
as) **
[Sending] : OPTIONS https://outlook.office365.com/Microsoft-Server-ActiveSync

** Wed Jan 18 2023 10:27:11 GMT+0100 (StYedoevropsk� standardn� 
as) **
[setSyncState] : State: oauthprompt, Account: M... T...

** Wed Jan 18 2023 10:27:11 GMT+0100 (StYedoevropsk� standardn� 
as) **
[EventLog] : OAuthServerError::{}

** Wed Jan 18 2023 10:27:11 GMT+0100 (StYedoevropsk� standardn� 
as) **
[EventLog] : OAuthServerError::{}

** Wed Jan 18 2023 10:27:11 GMT+0100 (StYedoevropsk� standardn� 
as) **
[setSyncState] : State: accountdone, Account: M... T...

```
## Steps to reproduce
Try to sync OAuth 2.0 MS Outlook mail account.

**Comment by mdiskuze** [comment]
Fixed by downgrade TB into version 102.4.2 ! This was my last hope :-). But I still think that TbSync or EAS Provider has some problem with TB version 102.7.0 ...

`sudo apt install thunderbird=1:102.4.2+build2-0ubuntu0.22.04.1`

**Comment by jobisoft** [comment]
[Here is some information about the change in 102.7:
https://thunderbird.topicbox.com/groups/enterprise/T262ef074c0833a12-Mb7dd2995cbea31000255ac10

**Comment by mdiskuze** [comment]
> Here is some information about the change in 102.7: https://thunderbird.topicbox.com/groups/enterprise/T262ef074c0833a12-Mb7dd2995cbea31000255ac10

Yes, this probably be the problem ... Thanks for this link, I will consult this with our ICT.

**Comment by jeron1** [comment]
Some info here too: https://www.reddit.com/r/Thunderbird/comments/yqwes1/notice_to_microsoft_office_365_enterprise_users/
Below is comment that I posted at link above:
"Single user of Microsoft 365 Business Basic on KDE neon 5.26. OAuth2 works fine on TB 102.4.2, but problem when upgrade to 102.7: password accepted in Msft dialogbox, SMS code appears to be accepted, but then a message appears in small TB pop-up "Authentication failure while connecting to server outlook.office365.com".  Everything works when downgrade from 102.7 back to 102.4.2."

**Comment by jobisoft** [comment]
The 102.7 update will not be shipped. Where did you get it from, by the way? The TB team has only released a candidate, but nothing official.

**Comment by fkn-iteratec** [comment]
I have also the problem with the 102.7.0 and it is installed on my Ubuntu Linux via snap. Not sure why there is a newer version than the official release page of thunderbird says.

**Comment by bnysten** [comment]
I have the same problems since yesterday when thunderbird was upgraded to 102.7.0 on Ubuntu 22.04.

**Comment by pulver22** [comment]
Same problem here, TB upgraded to 102.7.0 yesterday on PopOS 18.04 .

**Comment by BubuOT** [comment]
> The 102.7 update will not be shipped. Where did you get it from, by the way? The TB team has only released a candidate, but nothing official.

Updated automatically via snap on Ubuntu here.

**Comment by jeron1** [comment]
> 

It was an automatic update.  Per Muon: 
"Origin: Firefox ESR and Thunderbird stable builds".
![from muon 2023-01-19_10-13](https://user-images.githubusercontent.com/73413568/213480375-b5b65bad-3161-4b39-86df-5a7551de623b.png)
(I'm forcing 102.4.2 for now.)

**Comment by PresGas** [comment]
The mozillateam ppa just had another release of 102.7 

`Unpacking thunderbird (1:102.7.0+build1-0ubuntu0.22.04.2~mt1) over (1:102.7.0+build1-0ubuntu0.22.04.1~mt1)`

...but there was no change to status of OAuth.

**Comment by fkn-iteratec** [comment]
See also here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1810760

**Comment by kidmar** [comment]
I have the same problem with 102.7.1 (that fixed Thunderbird problem with Oauth2 and Office365).
When I try to sync the calendar a new window opens (that should ask for credentials, but this is the url:
https://undefined/?response_type=code&client_id=undefined&redirect_uri=http

Obviously it doesn't work and gives a "Cannot contact server" error

**Comment by namawakame** [comment]
Same problem as kidmar (https://github.com/jobisoft/TbSync/issues/645#issuecomment-1411875093) with a Microsoft 365 account and TB 102.7.1.  

Attempted to delete and then re-add the account but on adding I just get a "Server not found" error after entering a user name and clicking "Add account".  The M365 domain is a default xxxxx.onmicrosoft.com so I think the server should be discoverable.

**Comment by jobisoft** [comment]
> Hi, I'm really interested in this subject but not at the moment. I have tried to unsubscribe several times with no effect. Can you pls. remove me from this thread. Regards Juergen

There is an unsubscribe button on the top-ish right side of this page.

**Comment by BAnd313** [comment]
Seems fixed in latest beta, see comments in the official blog post: 

[https://blog.thunderbird.net/2023/01/important-message-for-microsoft-office-365-enterprise-users/#comment-3149](https://blog.thunderbird.net/2023/01/important-message-for-microsoft-office-365-enterprise-users/#comment-3149)

**Comment by kidmar** [comment]
> Seems fixed in latest beta, see comments in the official blog post:
> 
> https://blog.thunderbird.net/2023/01/important-message-for-microsoft-office-365-enterprise-users/#comment-3149

Thunderbird got fixed in 102.7.1 but TbSync still doesn't work

**Comment by BAnd313** [comment]
> > Seems fixed in latest beta, see comments in the official blog post:
> > https://blog.thunderbird.net/2023/01/important-message-for-microsoft-office-365-enterprise-users/#comment-3149
> 
> Thunderbird got fixed in 102.7.1 but TbSync still doesn't work

As Jason Evangelho said in his latest comment ([#comment-3138](https://blog.thunderbird.net/2023/01/important-message-for-microsoft-office-365-enterprise-users/#comment-3138)), 102.7.1 was not a definitive fix, since many users still faced this issue, so they pulled the update.

I can't log in with TB 102.7.1 either, regardless of TbSync

**Comment by kidmar** [comment]
> 

After that comment version 102.7.1 disappeared, but after some days they released it again with the same number.
The new version works for me.
Anyway this has nothing to do with TbSync (I think). It looks like TbSync uses a different authentication token and a different way to request it.
I have TB working with 102.7.1 but TbSync still isn't working so the two are not correlated.
TbSync and TB broke on 102.7.0 probably because of some underlying changes in the authentication process, TB addressed those breaking changes in 102.7.1 (for most people, but not for everyone) while TbSync still isn't working

**Comment by DerXteMensch** [comment]
> > 
> 
> After that comment version 102.7.1 disappeared, but after some days they released it again with the same number. The new version works for me. Anyway this has nothing to do with TbSync (I think). It looks like TbSync uses a different authentication token and a different way to request it. I have TB working with 102.7.1 but TbSync still isn't working so the two are not correlated. TbSync and TB broke on 102.7.0 probably because of some underlying changes in the authentication process, TB addressed those breaking changes in 102.7.1 (for most people, but not for everyone) while TbSync still isn't working

I can confirm this. However for me it looks like that the read process works with TbSync with version 102.7.1 (build 2 from this week). But if I add new elements to the calendar (so that TbSync needs to write), it doesn't work anymore and I get error {}

**Comment by danzone** [comment]
I just updated it on my Ubuntu 22.10 (Thunderbird build 1:102.7.1+build2-0ubuntu0.22.10.1 from https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu) and now it works (both Thunderbird Auth and TbSynch auth).

**Comment by danzone** [comment]
And now, after some time, I have the same error in TbSynch, while Thunderbird is still working. Really strange behaviour

**Comment by fgo-stei** [comment]
I can confirm Thunderbird got fixed in 102.7.1 but TbSync still doesn't work

**Comment by xtrailrunner** [comment]
> 



> > Hi, I'm really interested in this subject but not at the moment. I have tried to unsubscribe several times with no effect. Can you pls. remove me from this thread. Regards Juergen
> 
> There is an unsubscribe button on the top-ish right side of this page.

Yeah. But it does not work. Tried several times.

**Comment by jobisoft** [comment]
Fixed here?
https://github.com/jobisoft/EAS-4-TbSync/issues/215#issuecomment-1416725608

**Comment by wolffi** [comment]
> Fixed here? [jobisoft/EAS-4-TbSync#215 (comment)](https://github.com/jobisoft/EAS-4-TbSync/issues/215#issuecomment-1416725608)

This fixes it for me on TB 102.7.1! Thank you very much @jobisoft !

**Comment by albzotto** [comment]
Hello, I have same issue. Downloaded .zip file but I do not how use it. Thank you

**Comment by bermeitinger-b** [comment]
You install it from the Addons page in Thunderbird.

**Comment by albzotto** [comment]
Hello, I have same issue. Downloaded .zip file but I do not how use it. Thank you

**Comment by albzotto** [comment]
Great! It works! Thank you for support

**Comment by fgo-stei** [comment]
I followed the steps below to get it running:
1. Download the zip file
2. rename it to have .xpi extension in stead of .zip extension
3. Go into the Add on page in thunderbird, click on the gear icon and select to install from file
4. browse to the file, select and install it
5. Check that the active "Provider for Exchange ActiveSync" addon version is 4.2 (February 6th) 
6. Check that TbSync works in the active Thunderbird version
7. Update to TB102.107.1.2 
8. Check TbSync again 
This worked perfectly well for me

**Comment by mdiskuze** [comment]
> Fixed here? [jobisoft/EAS-4-TbSync#215 (comment)](https://github.com/jobisoft/EAS-4-TbSync/issues/215#issuecomment-1416725608)

Works for me in TB 102.7.1, thanks!
