### ISSUE TITLE
Sync not working after update from v0.7.7 to v0.7.9 or v0.7.10

### ISSUE THREAD

**Issue by Grimlin63** [jobisoft/TbSync#93]
## Your environment

TbSync version: v0.7.9
Thunderbird version: 52.8.0 (32-Bit)

[ ] Yes, I have installed the latest available version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
after install, deactivate and activate account. Sync started, but there ar no appointments.
All appontments, adresses and so on are lost in Thunderbird Lightning.
In former version v0.7.7 all working o.k.. 

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by Ri0n** [comment]
same here. just synced my cal with 0.7.7 and noticed the 0.7.9 update. Updated and it's just empty

**Comment by jobisoft** [comment]
What type of Server?
Could you remove(!) your account and set it up again, any change?

If not, could you follow these instructions 
https://github.com/jobisoft/TbSync/wiki/What-if-TbSync-is-blocked-by-my-server%3F

and set clientID.type to "Thunderbird"? Leave the useragent untouched/empty. Again remove (!) your account and set it up again, any change?

**Comment by Ri0n** [comment]
How can I understand type of outlook.office365.com ?
Readding account seems to work. But for some reason I've lost some other calendar events. I added manually a few, Now they are lost.

**Comment by Ri0n** [comment]
Just readded again, synced and again empty. Weird.

**Comment by jobisoft** [comment]
I tested outlook.office365.com and it works for me :-(

Are you just removing and readding your account or did you also play around with clientID.type?

**Comment by Ri0n** [comment]
May be the problem is in two accounts?
I just enabled debug logging, selected account which definitely has calendar events, clicked synchronize. And surprise! debug log has records only from another account!
But both accounts set status calendar is synchronized.

**Comment by jobisoft** [comment]
Please answer:
1. Did you change the value of cliendID.type?
2. You have setup two office365 accounts? One works and one does not?

**Comment by Ri0n** [comment]
1. Yes. I tried "Thunderbird". Nothing changed
2. Correct. but I'm not sure about another since it doesn't have remote calendar events. I'll try to add some and let you know.

**Comment by Ri0n** [comment]
None of them work..

**Comment by Ri0n** [comment]
Just in case it's thunderbird 52.8.0 on Ubuntu 18.04 with all extensions updated.

**Comment by Ri0n** [comment]
Here is what I have in debug log
```
** Thu Jun 28 2018 13:08:21 GMT+0300 **
[setSyncState] : State: connected, Account: EPAM

** Thu Jun 28 2018 13:08:21 GMT+0300 **
[setSyncState] : State: preparing, Account: EPAM, Folder: Calendar

** Thu Jun 28 2018 13:08:21 GMT+0300 **
[setSyncState] : State: prepare.request.estimate, Account: EPAM, Folder: Calendar

** Thu Jun 28 2018 13:08:21 GMT+0300 **
[setSyncState] : State: send.request.estimate, Account: EPAM, Folder: Calendar

** Thu Jun 28 2018 13:08:21 GMT+0300 **
[Sending (EAS v14.0)] : POST https://outlook.office365.com/Microsoft-Server-ActiveSync?Cmd=GetItemEstimate&User=name_changed%40epam.com&DeviceType=TbSync&DeviceId=mztb90b750hashwaschanged3d892

** Thu Jun 28 2018 13:08:21 GMT+0300 **
[setSyncState] : State: eval.response.estimate, Account: EPAM, Folder: Calendar

** Thu Jun 28 2018 13:08:21 GMT+0300 **
[Extracted XML data] : 
GetItemEstimate => 
 Response => 
  Status = [1]
  Collection => 
   CollectionId = [2]
   Estimate = [0]
  Collection <= 
 Response <= 
GetItemEstimate <= 


** Thu Jun 28 2018 13:08:21 GMT+0300 **
[setSyncState] : State: prepare.request.remotechanges, Account: EPAM, Folder: Calendar

** Thu Jun 28 2018 13:08:21 GMT+0300 **
[setSyncState] : State: send.request.remotechanges, Account: EPAM, Folder: Calendar

** Thu Jun 28 2018 13:08:21 GMT+0300 **
[Sending (EAS v14.0)] : POST https://outlook.office365.com/Microsoft-Server-ActiveSync?Cmd=Sync&User=name_changed%40epam.com&DeviceType=TbSync&DeviceId=mztb90b750hashwaschanged3d892

** Thu Jun 28 2018 13:08:22 GMT+0300 **
[setSyncState] : State: eval.response.remotechanges, Account: EPAM, Folder: Calendar

** Thu Jun 28 2018 13:08:22 GMT+0300 **
[setSyncState] : State: prepare.request.localchanges, Account: EPAM, Folder: Calendar

** Thu Jun 28 2018 13:08:22 GMT+0300 **
[finishFolderSync(EPAM.Calendar)] : Ok
```

**Comment by jobisoft** [comment]
I no longer suggest to change the clientID.type value, please undo/reset your changes.

Please make sure, that the online calendar truely contains events by logging into the webinterface of office 365.

**Comment by Ri0n** [comment]
![image](https://user-images.githubusercontent.com/52379/42028718-bb2a1b24-7ad5-11e8-9edd-535e0453eef0.png)

**Comment by Ri0n** [comment]
I removed one of accounts, just to make sure. same problem.
![x](https://user-images.githubusercontent.com/52379/42029252-9bb648a6-7ad7-11e8-99a2-432483cdc656.png)

![x](https://user-images.githubusercontent.com/52379/42029388-10bd93d4-7ad8-11e8-9d84-f0bb74629b6c.png)

**Comment by jobisoft** [comment]
This looks correct. I have no idea, what is going on. It would be interesting to know what happens if you do the following:

- delete the account in tbsync
- install tbsync 0.7.7
- add the account again
- status ?
- remove the account again
- install tbsync 0.7.9
- add the account again
- status ?

**Comment by Ri0n** [comment]
Doesn't work with 0.7.7 anymore

**Comment by Ri0n** [comment]
Reinstallation  of 0.7.9 with all the plays with account haven't changed anything.

**Comment by jobisoft** [comment]
Remove the account and upgrade to 0.7.9 again, but do not add your account again for now.

Is your IP address changing once a day, or is it fixed? Are you able to get another IP address, via VPN or something like that?

**Comment by jobisoft** [comment]
Remove the account and upgrade to 0.7.9 again, but do not add your account again for now.

Is your IP address changing once a day, or is it fixed? Are you able to get another IP address, via VPN or something like that?

**Comment by Ri0n** [comment]
I guess public IP is pretty much static. The one behind NAT can change probably (never checked and don't know dhcp settings).
I'll try later with vpn, have some work to do.

**Comment by jobisoft** [comment]
I *think* due to the changed device type on the account, office365 somehow put a block on your account. I do not know if it is limited to your public IP.

I know from other issues, that this block will go away, maybe because of IP change ? I do not know. This is all very strange.

So just let TbSync 0.7.9 sit there without any accounts and retry in a couple of days.

I am sorry for this issue.

**Comment by Ri0n** [comment]
OK. deleted account for now.

**Comment by jobisoft** [comment]
@Grimlin63 : What is your current situation?

**Comment by Grimlin63** [comment]
I deactivate 0.7.9 in Thunderbird (account not delete or change) and reinstall 0.7.7 fom a file. Then i started the sync. At 0.7.7 all working fine now. All data are and events are schown in Thunderbird.

**Comment by jobisoft** [comment]
But it will autoupdate to 0.7.9 soon.

Can you by any chance create a new thunderbird (test-)profile and start fresh with 0.7.9?

**Comment by jobisoft** [comment]
DO NOT USE 0.7.9

If you have updated, remove any account from the TbSync account manager and just let it sit there empty until further notice. Also please do not downgrade, because that could have unforeseen consequences as well.

**Comment by crbble** [comment]
Can you specify this a little bit? Does the do not use hint also apply for non office365 accounts? Is the auto updated thunderbird version 0.7.9 the same as the faulty one?

**Comment by jobisoft** [comment]
Up to now I only know about trouble with O365 and Exchange on-premise servers. I did make an error with 0.7.9 but it could be, that other servers do not care. But to make sure, I suggest to not use it anymore. 

I revoked 0.7.9 so it should no longer auto-update. If you have 0.7.9, than it is the faulty one. But please DO NOT downgrade, if you have 0.7.9 already. Just backup your data and after (!) you have done that, remove any account from the tbsync account manager.

I will release a new version today, which should fix the error (also by hard resetting tbsync and all server connection and adding some glue logic)

**Comment by jobisoft** [comment]
v0.7.10 is out. Please do make backups before installing it, just to make sure. This will happen, after you install 0.7.10:

 - all accounts will be resetted (disabled)
 - all local calendars and address books will be backuped

You should then be able to enable your accounts again and the current data avail on the server should sync down.

TbSync v0.7.10 can be downloaded [here](https://github.com/jobisoft/TbSync/releases/tag/v0.7.10)

**Comment by jobisoft** [comment]
Feedback on 0.7.10 is appreciated, so I can push it out via update channels

**Comment by Ri0n** [comment]
Just tried 0.7.10 on clear profile and on other machine/os/geo location/ip. Still shows nothing in calendar regardless of bunch of periodic events shown in the web version.

**Comment by Ri0n** [comment]
I've added an event for tomorrow, then synced from thunderbird. Nothing changed in thunderbird.

**Comment by jobisoft** [comment]
We have to consider this a WONTFIX. It looks like TbSync got banned by your server. I rendered TbSync useless for you. I do not see how I can fix that.

This is sad. Sorry.

**Comment by Ri0n** [comment]
Ok. Is there any other thunderbird extension to sync my calendar?

**Comment by jobisoft** [comment]
Not for ActiveSync. Besides the Exchange ActiveSync protocol (EAS), some providers also support the Exchange WebServices (EWS) protocol. There are also some Thunderbird Add-Ons supporting EWS (ExQuilla, Exchange EWS Provider)

**Comment by Ri0n** [comment]
Just in case. Just took a look on logs in web interface.
![image](https://user-images.githubusercontent.com/52379/42237064-64441e3e-7f05-11e8-9df4-e4515481f4db.png)
Nothing about banning anything.

**Comment by jobisoft** [comment]
Every image you have send me looks good. I just cannot tell you, why your server is not sending anything. The log you send me a few days ago simply states estimate=0 which means nothing to sync. From here I cannot do anymore. 

What happens if you click on the "learn more about syncing issues" link? 
What happens if you add items in thunderbird and sync them to your server?

**Comment by Ri0n** [comment]
After adding an event via thunderbird and clicking sync in tbsync the event created via web interfaces was synced to thunderbird and the local even was synced to remote.
So it seems it doesn't work only when there is nothing local to sync.

 "learn more about syncing issues" leads Google Chrome to get stuck.

**Comment by jobisoft** [comment]
That is GOOD news! But that bug needs investigation. Please make sure there are no local changes and add a new entry in the web and sync. If that is a general bug, that item should not show up in TB...

**Comment by Ri0n** [comment]
it synced too.
Then I removed all the events clicked sync. It worked, so all events were removed. Then again added one via web, ckicked sync. worked again.
So I can't reproduce it anymore.

**Comment by jobisoft** [comment]
I added this entry to the troubleshooting section:
https://github.com/jobisoft/TbSync/wiki/Troubleshooting#office-365-and-maybe-other-microsoft-servers

That is the best I can take out of this issue. Can I close this? Thank for your help!

**Comment by Ri0n** [comment]
Ok.

**Comment by Ri0n** [comment]
Just tried same trick on another machine. First it failed with error
```
** Wed Jul 04 2018 16:11:58 GMT+0300 **
[Bad item skipped <Invalid item! Mandatory fields missing? Dublicate item?>] : 
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Minsk
BEGIN:STANDARD
TZOFFSETFROM:+0300
TZOFFSETTO:+0300
TZNAME:+03
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20180704T131118Z
LAST-MODIFIED:20180704T131146Z
DTSTAMP:20180704T131146Z
UID:bf5a7f57-137d-42ea-92c3-ece41f3f3518
SUMMARY:New Event
DTSTART;TZID=Europe/Minsk:20180704T164500
DTEND;TZID=Europe/Minsk:20180704T174500
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```
but after a few minutes it started working.
